name: examples/httpserver-rust1.73 (stable)

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
    - '.github/workflows/example-httpserver-rust1.73-stable.yaml'
    - 'httpserver-rust1.73/**'
    - '!httpserver-rust1.73/README.md'

  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
    paths:
    - '.github/workflows/example-httpserver-rust1.73-stable.yaml'
    - 'httpserver-rust1.73/**'
    - '!httpserver-rust1.73/README.md'

  schedule:
  - cron: '45 15 * * 1-5'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  UKC_METRO: "https://api.${{ vars.UKC_METRO_STABLE }}.unikraft.cloud/v1"
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  KRAFTKIT_NO_CHECK_UPDATES: true
  KRAFTKIT_LOG_LEVEL: debug

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      id: test
      uses: unikraft/kraftkit@staging
      with:
        run: |
          set -xe;

          cd httpserver-rust1.73;

          kraft cloud deploy \
            --no-start \
            --name httpserver-rust173-${GITHUB_RUN_ID} \
            --runtime index.unikraft.io/official-testing/base-compat:latest \
            --subdomain httpserver-rust173-${GITHUB_RUN_ID} \
            -p 443:8080 \
            -M 256 \
            .;

          # wait for the instance to start
          kraft cloud vm start -w 5s httpserver-rust173-${GITHUB_RUN_ID};
          sleep 5;

          curl -Lv --fail-with-body --max-time 10 https://httpserver-rust173-${GITHUB_RUN_ID}.${{ vars.UKC_METRO_STABLE }}.unikraft.app

    - name: Cleanup
      uses: unikraft/kraftkit@staging
      if: always()
      with:
        run: |
          set -xe;

          kraft cloud vm stop httpserver-rust173-${GITHUB_RUN_ID} || true;
          kraft cloud vm logs httpserver-rust173-${GITHUB_RUN_ID} || true;
          kraft cloud vm rm httpserver-rust173-${GITHUB_RUN_ID} || true;
          kraft cloud img rm index.unikraft.io/test/httpserver-rust173-${GITHUB_RUN_ID} || true;
