name: examples/node-playwright-firefox (staging)

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
    - '.github/workflows/example-node-playwright-firefox-staging.yaml'
    - 'node-playwright-firefox/**'
    - '!node-playwright-firefox/README.md'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
    - '.github/workflows/example-node-playwright-firefox-staging.yaml'
    - 'node-playwright-firefox/**'
    - '!node-playwright-firefox/README.md'

  schedule:
  - cron: '45 16 * * 1-5'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  UKC_METRO: "https://api.${{ vars.UKC_METRO_STAGING }}.unikraft.cloud/v1"
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  KRAFTKIT_NO_CHECK_UPDATES: true
  KRAFTKIT_LOG_LEVEL: debug

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      id: test
      uses: unikraft/kraftkit@staging
      with:
        run: |
          set -xe;

          sudo apt-get -y update;
          sudo apt-get install -y --no-install-recommends file grep;

          cd node-playwright-firefox;

          kraft cloud deploy \
            --no-start \
            --memory 4096 \
            --name node-playwright-firefox-${GITHUB_RUN_ID} \
            --runtime index.unikraft.io/official-staging/base-compat:latest \
            --subdomain node-playwright-firefox-${GITHUB_RUN_ID} \
            -p 443:8080 \
            .;

          # wait for the instance to start
          kraft cloud vm start -w 5s node-playwright-firefox-${GITHUB_RUN_ID};
          sleep 5;

          curl -Lv --fail-with-body --max-time 10 --output screenshot.png "https://node-playwright-firefox-${GITHUB_RUN_ID}.${{ vars.UKC_METRO_STAGING }}.unikraft.app/?page=https://google.com"
          file screenshot.png | grep -q PNG

    - name: Cleanup
      uses: unikraft/kraftkit@staging
      if: always()
      with:
        run: |
          set -xe;

          kraft cloud vm stop node-playwright-firefox-${GITHUB_RUN_ID} || true;
          kraft cloud vm logs node-playwright-firefox-${GITHUB_RUN_ID} || true;
          kraft cloud vm rm node-playwright-firefox-${GITHUB_RUN_ID} || true;
          kraft cloud img rm index.unikraft.io/test/node-playwright-firefox-${GITHUB_RUN_ID} || true;
