name: examples/node18-nextjs (staging)

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
    - '.github/workflows/example-node18-nextjs-staging.yaml'
    - 'node18-nextjs/**'
    - '!node18-nextjs/README.md'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
    - '.github/workflows/example-node18-nextjs-staging.yaml'
    - 'node18-nextjs/**'
    - '!node18-nextjs/README.md'

  schedule:
  - cron: '15 16 * * 1-5'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  UKC_METRO: "https://api.${{ vars.UKC_METRO_STAGING }}.unikraft.cloud/v1"
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  KRAFTKIT_NO_CHECK_UPDATES: true
  KRAFTKIT_LOG_LEVEL: debug

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      id: test
      uses: unikraft/kraftkit@staging
      with:
        run: |
          set -xe;

          cd node21-nextjs;

          kraft cloud deploy \
            --no-start \
            --memory 756 \
            --name node18-nextjs-staging-${GITHUB_RUN_ID} \
            --runtime index.unikraft.io/official-staging/base-compat:latest \
            --subdomain node18-nextjs-staging-${GITHUB_RUN_ID} \
            -p 443:3000 \
            .;

          # wait for the instance to start
          kraft cloud vm start -w 5s node18-nextjs-staging-${GITHUB_RUN_ID};
          sleep 5;

          curl -Lv --fail-with-body --max-time 10 https://node18-nextjs-staging-${GITHUB_RUN_ID}.${{ vars.UKC_METRO_STAGING }}.unikraft.app

    - name: Cleanup
      uses: unikraft/kraftkit@staging
      if: always()
      with:
        run: |
          set -xe;

          kraft cloud vm stop node18-nextjs-staging-${GITHUB_RUN_ID} || true;
          kraft cloud vm logs node18-nextjs-staging-${GITHUB_RUN_ID} || true;
          kraft cloud vm rm node18-nextjs-staging-${GITHUB_RUN_ID} || true;
          kraft cloud img rm index.unikraft.io/test/node18-nextjs-staging-${GITHUB_RUN_ID} || true;
