name: examples/nginx (stable)

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
    - '.github/workflows/example-nginx-stable.yaml'
    - 'nginx/**'
    - '!nginx/README.md'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
    - '.github/workflows/example-nginx-stable.yaml'
    - 'nginx/**'
    - '!nginx/README.md'

  schedule:
  - cron: '0 16 * * 1-5'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  UKC_METRO: "https://api.${{ vars.UKC_METRO_STABLE }}.unikraft.cloud/v1"
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  KRAFTKIT_NO_CHECK_UPDATES: true
  KRAFTKIT_LOG_LEVEL: debug

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      id: test
      uses: unikraft/kraftkit@staging
      continue-on-error: true
      with:
        run: |
          set -xe;

          cd nginx;

          kraft cloud deploy \
            --no-start \
            --memory 256 \
            --name nginx-${GITHUB_RUN_ID} \
            --runtime index.unikraft.io/official-testing/base-compat:latest \
            --subdomain nginx-${GITHUB_RUN_ID} \
            -p 443:8080 \
            .;

          # wait for the instance to start
          kraft cloud vm start -w 5s nginx-${GITHUB_RUN_ID};
          sleep 5;

          curl -Lv --fail-with-body --max-time 10 https://nginx-${GITHUB_RUN_ID}.${{ vars.UKC_METRO_STABLE }}.unikraft.app

    - name: Cleanup
      uses: unikraft/kraftkit@staging
      if: always()
      with:
        run: |
          set -xe;

          kraft cloud vm stop nginx-${GITHUB_RUN_ID} || true;
          kraft cloud vm logs nginx-${GITHUB_RUN_ID} || true;
          kraft cloud vm rm nginx-${GITHUB_RUN_ID} || true;
          kraft cloud img rm index.unikraft.io/test/nginx-${GITHUB_RUN_ID} || true;
